apiVersion: v1
kind: Service
metadata:
  labels:
    qcloud-app: auth
  name: auth
  namespace: test
spec:
  ports:
  - name: tcp-9301-9301
    port: 9301
    protocol: TCP
    targetPort: 9301
  selector:
    qcloud-app: auth
  sessionAffinity: None
  type: LoadBalancer

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    qcloud-app: auth
  name: auth
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      qcloud-app: auth
  template:
    metadata:
      labels:
        qcloud-app: auth
    spec:
      containers:
      - image: REGISTRY/RNS/NAME_TAG
        imagePullPolicy: IfNotPresent
        name: auth
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 1Gi
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
      imagePullSecrets:
      - name: qcloudregistrykey
      restartPolicy: Always
